export const INPUT_SEARCH_DEBOUNCE_TIME = 300;
export const FETCH_ALL_CHACTER_LIMIT = 50;
export const FETCH_COMICS_BY_CHACTER_ID_LIMIT = 50;
export const FETCH_ALL_CHACTER_LIMIT_LIGHT = 5;
export const FETCH_COMICS_BY_CHACTER_ID_LIMIT_LIGHT = 5;
